import json
import os
import argparse
import sys
from typing import List, Dict, Any
from tqdm import tqdm

def load_json(path: str) -> Any:
    """
    加载 JSON 文件并进行基础的路径检查。
    """
    if not os.path.exists(path):
        print(f"[ERROR] File not found: {path}")
        sys.exit(1)
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except json.JSONDecodeError as e:
        print(f"[ERROR] Failed to decode JSON from {path}: {e}")
        sys.exit(1)

def save_json(data: Any, path: str) -> None:
    """
    将数据保存为 JSON 文件。
    """
    with open(path, 'w') as f:
        json.dump(data, f)
    print(f"[INFO] Successfully saved to {path}")

def fix_scene_metadata(data_root: str, dataset_folder: str = 'advanced_12Hz_trainval') -> None:
    """
    核心修复逻辑：
    读取 sample.json 作为事实依据（Source of Truth），
    重构 scene.json 中的元数据（nbr_samples, first_sample_token, last_sample_token）。
    
    Args:
        data_root: NuScenes 数据集根目录。
        dataset_folder: ASAP 生成的目标数据集文件夹名称。
    """
    target_dir = os.path.join(data_root, dataset_folder)
    sample_json_path = os.path.join(target_dir, 'sample.json')
    scene_json_path = os.path.join(target_dir, 'scene.json')

    print(f"[INFO] Target Directory: {target_dir}")
    
    # 1. 加载数据
    print("[INFO] Loading 'sample.json'...")
    samples: List[Dict[str, Any]] = load_json(sample_json_path)
    
    print("[INFO] Loading 'scene.json'...")
    scenes: List[Dict[str, Any]] = load_json(scene_json_path)

    # 2. 建立索引映射：Scene Token -> List[Sample]
    # 这一步是必要的，因为我们需要获取属于特定场景的所有样本以确定其首尾帧
    print("[INFO] Indexing samples by scene_token...")
    scene_to_samples: Dict[str, List[Dict[str, Any]]] = {scene['token']: [] for scene in scenes}
    
    for sample in tqdm(samples, desc="Indexing"):
        s_token = sample['scene_token']
        if s_token in scene_to_samples:
            scene_to_samples[s_token].append(sample)
        else:
            # 这种情况通常不应发生，除非 scene.json 与 sample.json 严重不匹配
            continue

    # 3. 修正元数据
    print("[INFO] Updating scene metadata...")
    updated_count = 0
    skipped_count = 0
    fixed_scenes = []

    for scene in tqdm(scenes, desc="Fixing"):
        s_token = scene['token']
        related_samples = scene_to_samples.get(s_token, [])

        # 如果该场景下无样本（可能在生成过程中被过滤），则跳过并不予修改
        if not related_samples:
            skipped_count += 1
            fixed_scenes.append(scene)
            continue

        # 关键步骤：按时间戳严格排序
        # ASAP 生成的数据可能存在多线程写入导致的乱序风险，必须重新排序以确保链表正确性
        related_samples.sort(key=lambda x: x['timestamp'])

        # 获取真实统计数据
        real_count = len(related_samples)
        real_first_token = related_samples[0]['token']
        real_last_token = related_samples[-1]['token']

        # 检查并更新差异
        if (scene['nbr_samples'] != real_count or 
            scene['first_sample_token'] != real_first_token or 
            scene['last_sample_token'] != real_last_token):
            
            scene['nbr_samples'] = real_count
            scene['first_sample_token'] = real_first_token
            scene['last_sample_token'] = real_last_token
            updated_count += 1
        
        fixed_scenes.append(scene)

    # 4. 保存结果
    save_json(fixed_scenes, scene_json_path)

    # 5. 输出统计报告
    print("-" * 50)
    print(f"[SUMMARY] Processing Complete.")
    print(f"Total Scenes:      {len(scenes)}")
    print(f"Updated Scenes:    {updated_count}")
    print(f"Skipped Scenes:    {skipped_count}")
    print("-" * 50)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Fix inconsistencies in scene.json generated by ASAP.")
    parser.add_argument('--data_root', type=str, default='./data/nuscenes', 
                        help='Path to the nuscenes root directory.')
    parser.add_argument('--dataset_folder', type=str, default='advanced_12Hz_trainval',
                        help='Name of the generated dataset folder.')
    
    args = parser.parse_args()
    
    fix_scene_metadata(args.data_root, args.dataset_folder)


"""
python ./sAP3D/fill_12Hz_scene_json.py \
    --data_root ./data/nuscenes \
    --dataset_folder advanced_12Hz_mini


python ./sAP3D/ffill_12Hz_scene_json.py \
    --data_root ./data/nuscenes \
    --dataset_folder advanced_12Hz_full_mini

"""